version: "2"
run:
  go: "1.23"

linters:
  enable:
    - "bodyclose"
    - "copyloopvar"
    - "errcheck"
    - "goheader"
    - "gosec"
    - "govet"
    - "ineffassign"
    - "nilerr"
    - "nolintlint"
    - "predeclared"
    - "revive"
    - "staticcheck"
    - "tparallel"
    - "unconvert"
    - "unused"
    - "unparam"
    - "whitespace"

formatters:
  enable:
    - "gci"
    - "gofumpt"
  settings:
    # Enforces import order in Go source files
    gci:
      sections:
        - "standard"
        - "default"
        - "localmodule"
      custom-order: true
